# Generated by Django 4.0.4 on 2022-05-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_estudiantes_correo_estudiantes_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='clases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estudiante', models.CharField(max_length=100)),
                ('asignatura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
            ],
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='correo',
            field=models.CharField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='numero',
            field=models.CharField(max_length=100, verbose_name='Numero'),
        ),
    ]
