# Generated by Django 4.0.4 on 2022-05-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_asignaturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturas',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.profesor'),
        ),
    ]
