# Generated by Django 4.0.4 on 2022-05-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_asignaturas_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.IntegerField(max_length=100),
        ),
    ]
