# Generated by Django 4.0.4 on 2022-05-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_alter_profesor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
